# Generated by Django 4.2 on 2023-04-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LandRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("land_name", models.CharField(max_length=255)),
                ("land_value", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Others",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("others_name", models.CharField(max_length=255)),
                ("others_value", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SocialSecurity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract", models.CharField(max_length=255)),
                ("s_value", models.IntegerField()),
            ],
        ),
    ]
