# Generated by Django 4.2 on 2023-04-22 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialSecurity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract", models.CharField(max_length=255)),
                ("s_value", models.IntegerField()),
                ("time", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Others",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("others_name", models.CharField(max_length=255)),
                ("others_value", models.BigIntegerField()),
                ("time", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LandRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("land_name", models.CharField(max_length=255)),
                ("land_value", models.BigIntegerField()),
                ("time", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.person",
                    ),
                ),
            ],
        ),
    ]
