# Generated by Django 4.2 on 2023-04-19 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Influx",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.BigIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("salary", "SALARY"), ("others", "OTHERS")],
                        max_length=7,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("id_number", models.CharField(max_length=13, unique=True)),
                ("balance", models.BigIntegerField(default=0)),
                (
                    "influxes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.influx"
                    ),
                ),
                (
                    "land_registry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="institutions.landregistry",
                    ),
                ),
                (
                    "other",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="institutions.others",
                    ),
                ),
                (
                    "social_security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="institutions.socialsecurity",
                    ),
                ),
            ],
        ),
    ]
