# Generated by Django 4.2 on 2023-04-22 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("blacklisted", models.BooleanField(default=False)),
                ("surname", models.CharField(max_length=255)),
                ("id_number", models.CharField(max_length=13, unique=True)),
                ("balance", models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Influx",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.BigIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("salary", "SALARY"), ("others", "OTHERS")],
                        max_length=7,
                    ),
                ),
                ("time", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Efflux",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.BigIntegerField()),
                ("type", models.CharField(max_length=255)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("small", "SMALL"),
                            ("medium", "MEDIUM"),
                            ("large", "LARGE"),
                        ],
                        max_length=7,
                    ),
                ),
                ("time", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.person",
                    ),
                ),
            ],
        ),
    ]
